export const ventures = [
  {
    id: 'ebitans',
    step: '01',
    eyebrow: '01 / FLAGSHIP',
    title: 'eBitans',
    description:
      'A full-service digital agency crafting custom software for startups to enterprises. My flagship venture — where most of those 500+ projects were born.',
    accentColor: '#C8A56A',
    logo: '/images/logos/projects/ebitans-light.png',
    cardType: 'stats' as const,
    stats: {
      role: 'Founder · CTO',
      clients: '200+',
      founded: '2019',
    },
  },
  {
    id: 'wavebox',
    step: '02',
    eyebrow: '02 / MEDIA',
    title: 'WaveBox',
    description:
      'A modern media streaming platform built for creators. Scalable video delivery, creator tools, and audience analytics under one roof.',
    accentColor: '#B88B55',
    logo: '/images/logos/projects/wavebox-light.png',
    cardType: 'tags' as const,
    tags: ['React Native', 'Node.js', 'AWS', 'Firebase'],
    status: 'BUILDING',
  },
  {
    id: 'nirapod-qr',
    step: '03',
    eyebrow: '03 / SAFETY',
    title: 'Nirapod QR',
    description:
      'Safety-first QR code solutions — designed for emergencies, verification, and trust. A product built for real-world impact.',
    accentColor: '#D7B57F',
    logo: '/images/logos/projects/nirapod-light.png',
    cardType: 'qr' as const,
  },
  {
    id: 'ecommercex',
    step: '04',
    eyebrow: '04 / COMMERCE',
    title: 'eCommerceX',
    description:
      'Next-generation e-commerce platform. Headless architecture, blazing-fast storefronts, and a seller experience that just works.',
    accentColor: '#A67C52',
    logo: '/images/logos/projects/ecommercex-light.png',
    cardType: 'commerce' as const,
    gmv: '$2M+',
  },
]

export const projects = [
  {
    id: '1',
    name: 'eBitans Platform',
    category: 'Web' as const,
    year: '2024',
    techStack: ['Next.js', 'Node.js', 'PostgreSQL'],
    image: '/images/logos/projects/ebitans-light.png',
    link: '#',
    description: 'Full-service agency platform serving 200+ clients worldwide.',
  },
  {
    id: '2',
    name: 'WaveBox Streaming',
    category: 'SaaS' as const,
    year: '2023',
    techStack: ['React Native', 'Node.js', 'AWS'],
    image: '/images/logos/projects/wavebox-light.png',
    link: '#',
    description: 'Scalable media streaming platform for content creators.',
  },
  {
    id: '3',
    name: 'Nirapod QR Safety',
    category: 'Web' as const,
    year: '2023',
    techStack: ['Next.js', 'TypeScript', 'MongoDB'],
    image: '/images/logos/projects/nirapod-light.png',
    link: '#',
    description: 'Emergency QR code verification platform.',
  },
  {
    id: '4',
    name: 'eCommerceX Store',
    category: 'E-commerce' as const,
    year: '2024',
    techStack: ['Next.js', 'GraphQL', 'Redis'],
    image: '/images/logos/projects/ecommercex-light.png',
    link: '#',
    description: 'Headless e-commerce platform with blazing-fast storefronts.',
  },
  {
    id: '5',
    name: 'GP Internal Tools',
    category: 'Web' as const,
    year: '2018',
    techStack: ['React', 'Node.js', 'PostgreSQL'],
    image: '/images/projects/placeholder.jpg',
    link: '#',
    description: 'Internal tooling for Grameenphone operations.',
  },
  {
    id: '6',
    name: 'eCourier Backend',
    category: 'SaaS' as const,
    year: '2019',
    techStack: ['Node.js', 'Docker', 'AWS'],
    image: '/images/projects/placeholder.jpg',
    link: '#',
    description: 'High-scale logistics backend infrastructure.',
  },
  {
    id: '7',
    name: 'Restaurant POS',
    category: 'Web' as const,
    year: '2022',
    techStack: ['React', 'Node.js', 'MongoDB'],
    image: '/images/projects/placeholder.jpg',
    link: '#',
    description: 'Comprehensive point-of-sale system for restaurants.',
  },
  {
    id: '8',
    name: 'Healthcare App',
    category: 'Mobile' as const,
    year: '2022',
    techStack: ['Flutter', 'Firebase', 'Node.js'],
    image: '/images/projects/placeholder.jpg',
    link: '#',
    description: 'Telemedicine app connecting patients with doctors.',
  },
  {
    id: '9',
    name: 'EdTech Platform',
    category: 'SaaS' as const,
    year: '2021',
    techStack: ['Next.js', 'GraphQL', 'PostgreSQL'],
    image: '/images/projects/placeholder.jpg',
    link: '#',
    description: 'Online learning management system for 10K+ students.',
  },
  {
    id: '10',
    name: 'FinTech Dashboard',
    category: 'Web' as const,
    year: '2023',
    techStack: ['React', 'TypeScript', 'Redis'],
    image: '/images/projects/placeholder.jpg',
    link: '#',
    description: 'Real-time financial analytics dashboard.',
  },
]

export type ProjectCategory = 'All' | 'Web' | 'Mobile' | 'SaaS' | 'E-commerce'

export const timeline = [
  {
    year: '2014',
    role: 'CS Graduate',
    company: 'North South University',
    description: 'Graduated with a CS degree and a burning desire to build. Spent nights coding freelance projects — the beginning of 500+.',
    side: 'right' as const,
  },
  {
    year: '2015',
    role: 'Junior Developer',
    company: 'Early Career',
    description: 'First professional role. Learned to write production-grade code, work in teams, and ship on deadlines.',
    side: 'left' as const,
  },
  {
    year: '2016',
    role: 'Software Engineer',
    company: 'Grameenphone',
    description: 'Built internal tools used by thousands of employees across Bangladesh\'s largest telecom. Learned enterprise-scale systems.',
    side: 'right' as const,
  },
  {
    year: '2018',
    role: 'Senior Engineer',
    company: 'eCourier',
    description: 'Led backend infrastructure for one of Bangladesh\'s top courier platforms. Scaled systems from scratch to handle thousands of daily deliveries.',
    side: 'left' as const,
  },
  {
    year: '2019',
    role: 'Founder & CTO',
    company: 'eBitans',
    description: 'Founded eBitans — a digital agency built on craft. Traded a salary for a mission. Never looked back.',
    side: 'right' as const,
  },
  {
    year: '2021',
    role: 'Founder',
    company: 'WaveBox',
    description: 'Launched WaveBox, a media streaming platform for creators. Expanded from agency to product.',
    side: 'left' as const,
  },
  {
    year: '2023',
    role: 'Founder',
    company: 'Nirapod QR',
    description: 'Launched Nirapod QR — safety-first QR products for emergencies and verification. Building for real-world impact.',
    side: 'right' as const,
  },
  {
    year: '2024',
    role: 'Founder',
    company: 'eCommerceX',
    description: 'Launched eCommerceX — headless e-commerce for modern sellers. $2M+ GMV in first year.',
    side: 'left' as const,
  },
  {
    year: 'Now',
    role: 'CTO & Builder',
    company: '4 Ventures · 500+ Projects',
    description: 'Still writing code every day. Still obsessed with craft. Running 4 ventures, serving 50+ clients, and building what\'s next.',
    side: 'right' as const,
  },
]

export const testimonials = [
  {
    quote:
      'Hasib delivered a complex SaaS platform in half the time we expected — without sacrificing quality. His technical depth and product thinking are rare in the same person.',
    name: 'Rafiq Ahmed',
    role: 'CEO',
    company: 'TechVenture BD',
    initials: 'RA',
  },
  {
    quote:
      'Working with Hasib felt like having a CTO on demand. He didn\'t just build what we asked for — he pushed back on the right things and made our product significantly better.',
    name: 'Sarah Johnson',
    role: 'Founder',
    company: 'StartupHub',
    initials: 'SJ',
  },
  {
    quote:
      'The e-commerce platform eBitans built for us handles 10K daily orders without breaking a sweat. Incredible engineering and even better communication throughout.',
    name: 'Mohammad Karim',
    role: 'Director',
    company: 'RetailBD',
    initials: 'MK',
  },
  {
    quote:
      'Hasib is the kind of developer who understands business, not just code. He helped us architect a solution that scaled from 100 to 100,000 users.',
    name: 'Priya Sharma',
    role: 'CTO',
    company: 'GrowthSaaS',
    initials: 'PS',
  },
  {
    quote:
      'From MVP to production in 6 weeks. Hasib\'s team at eBitans made it look easy — but the quality speaks to the years of expertise behind every decision.',
    name: 'James Wilson',
    role: 'Product Manager',
    company: 'FinTech Co',
    initials: 'JW',
  },
]

export const stats = [
  { value: 500, suffix: '+', label: 'Projects delivered' },
  { value: 10, suffix: '+', label: 'Years experience' },
  { value: 4, suffix: '', label: 'Ventures founded' },
  { value: 50, suffix: '+', label: 'Happy clients' },
]

export const services = [
  {
    id: 'fullstack',
    icon: 'web',
    title: 'Full-Stack Web Apps',
    description: 'Production-grade React, Next.js, Node.js applications. From MVP to enterprise scale.',
    tags: ['React', 'Next.js', 'Node', 'PostgreSQL'],
    span: 'col-span-2 row-span-2',
    gradient: 'from-accent-gold/8 to-transparent',
  },
  {
    id: 'mobile',
    icon: 'mobile',
    title: 'Mobile Apps',
    description: 'Native feel with React Native and Flutter. Shipped to stores with 100K+ users.',
    tags: ['React Native', 'Flutter'],
    span: 'col-span-1 row-span-1',
    gradient: 'from-bg-tertiary to-bg-elevated',
  },
  {
    id: 'saas',
    icon: 'rocket',
    title: 'SaaS & MVPs',
    description: 'Rapid prototyping for startups. Go from idea to launched product in weeks.',
    tags: ['Startups', 'MVPs'],
    span: 'col-span-1 row-span-1',
    gradient: 'from-bg-tertiary to-bg-elevated',
  },
  {
    id: 'cto',
    icon: 'compass',
    title: 'CTO as a Service',
    description:
      'Technical leadership for startups that aren\'t ready to hire a full-time CTO. Architecture reviews, team building, technology strategy.',
    tags: ['Architecture', 'Leadership', 'Strategy'],
    badge: 'Most requested',
    span: 'col-span-2 row-span-1',
    gradient: 'from-accent-cyan/5 to-transparent',
  },
  {
    id: 'consulting',
    icon: 'consulting',
    title: 'Tech Consulting',
    description: 'Architecture reviews, code audits, scaling strategy.',
    tags: ['Audits', 'Scaling'],
    span: 'col-span-1 row-span-1',
    gradient: 'from-bg-tertiary to-bg-elevated',
  },
]

export const techStack = [
  'React',
  'Next.js',
  'Node.js',
  'TypeScript',
  'PostgreSQL',
  'MongoDB',
  'AWS',
  'Docker',
  'Flutter',
  'React Native',
  'GraphQL',
  'Redis',
  'Firebase',
  'Tailwind CSS',
  'Prisma',
]
